export type FooterBadge = FooterBadgeImage | FooterBadgeText;

type FooterBadgeBase = {
  name: string;
  url: string;
  alt: string;
  dofollow?: boolean;
  rel?: string;
  newTab?: boolean;
  title?: string;
};

export type FooterBadgeImage = FooterBadgeBase & {
  kind?: "image";
  image: string;
  width: number;
  height: number;
};

export type FooterBadgeText = FooterBadgeBase & {
  kind: "text";
  text: string;
};

export const footerBadges = [
  {
    name: "Fazier",
    image: "https://fazier.com/api/v1//public/badges/launch_badges.svg?badge_type=launched&theme=neutral",
    url: "https://fazier.com/launches/pinpointanswertoday.app",
    alt: "Fazier badge",
    width: 120,
    height: 36,
    dofollow: true,
  },
  {
    name: "ToolPilot",
    image: "https://www.toolpilot.ai/cdn/shop/files/f-b_690x151_crop_center.png?v=1695882701",
    url: "https://www.toolpilot.ai/",
    alt: "Featured on ToolPilot",
    width: 300,
    height: 66,
    dofollow: true,
  },
  {
    kind: "text",
    name: "MossAI Tools",
    text: "MossAI Tools",
    url: "https://mossai.org",
    alt: "MossAI Tools",
    title: "MossAI Tools",
    dofollow: true,
  },
  {
    kind: "text",
    name: "Pixel Art Village",
    text: "Pixel Art Village",
    url: "https://pixelartvillage.org/",
    alt: "Pixel Art Village",
    title: "Pixel Art Village",
    dofollow: true,
  },
  {
    kind: "text",
    name: "Micro SaaS Examples",
    text: "Micro SaaS Examples",
    url: "https://www.microsaasexamples.com/",
    alt: "Micro SaaS Examples",
    title: "Micro SaaS Examples",
    dofollow: true,
  },
  {
    kind: "text",
    name: "Z-Image",
    text: "Z-Image",
    url: "https://z-image.net/",
    alt: "Z-Image",
    title: "Z-Image",
    dofollow: true,
  },
  {
    kind: "text",
    name: "AI Tool Trek",
    text: "AI Tool Trek",
    url: "https://aitooltrek.com",
    alt: "AI Tool Trek",
    title: "AI Tool Trek",
    dofollow: true,
  },
  {
    kind: "text",
    name: "YP for AI",
    text: "YP for AI",
    url: "https://ypforai.com/",
    alt: "YP for AI",
    title: "YP for AI",
    dofollow: true,
  },
  {
    kind: "text",
    name: "IndieAI Directory",
    text: "Listed on IndieAI Directory",
    url: "https://indieai.directory/",
    alt: "Listed on IndieAI Directory",
    title: "Listed on IndieAI Directory",
    dofollow: true,
  },
  {
    name: "BuildWay",
    image: "https://www.buildway.cc/logo.png",
    url: "https://www.buildway.cc",
    alt: "Listed on BuildWay",
    width: 54,
    height: 54,
    dofollow: true,
  },
  {
    name: "NewTool.site",
    image: "https://newtool.site/badges/newtool-light.svg",
    url: "https://newtool.site/item/pinpoint-answer-today",
    alt: "Featured on NewTool.site",
    width: 210,
    height: 54,
    dofollow: true,
  },
  {
    name: "ShowMeBestAI",
    image: "https://showmebest.ai/badge/feature-badge-white.webp",
    url: "https://showmebest.ai",
    alt: "Featured on ShowMeBestAI",
    width: 220,
    height: 55,
    dofollow: true,
  },
  {
    name: "Aback Launch",
    image: "https://abacklaunch.com/badges/listed-on-blue.svg",
    url: "https://abacklaunch.com",
    alt: "Listed on Aback Launch",
    width: 160,
    height: 44,
    dofollow: true,
  },
  {
    name: "SaaSTool.site",
    image: "https://saastool.site/badges/saastool-light.svg",
    url: "https://saastool.site/item/pinpoint-answer-today",
    alt: "Featured on SaaSTool.site",
    width: 210,
    height: 54,
    dofollow: true,
  },
  {
    name: "yo.directory",
    image: "https://cdn.prod.website-files.com/65c1546fa73ea974db789e3d/65e1e171f89ebfa7bd0129ac_yodirectory-featured.png",
    url: "https://yo.directory/",
    alt: "yo.directory",
    width: 150,
    height: 54,
    dofollow: true,
  },
  {
    name: "Top Free AI Tools",
    image: "https://ff65dcf08ebd5eb1c022b44dd88016ac.cdn.bubble.io/f1724746111294x515859147102912600/badge%20black.png",
    url: "https://topfreeaitools.com/ai/pinpoint-answer-today",
    alt: "Featured on Top Free AI Tools",
    width: 230,
    height: 54,
    dofollow: true,
  },
  {
    name: "Turbo0",
    image: "https://img.turbo0.com/badge-listed-light.svg",
    url: "https://turbo0.com/item/pinpoint-answer-today",
    alt: "Listed on Turbo0",
    width: 150,
    height: 54,
    dofollow: true,
  },
  {
    name: "DeepLaunch.io",
    image: "https://deeplaunch.io/badge/badge_light.svg",
    url: "https://deeplaunch.io/",
    alt: "Featured on DeepLaunch.io",
    width: 200,
    height: 54,
    dofollow: true,
    newTab: false,
  },
  {
    name: "JustSimple Tools",
    image: "https://www.justsimple.tools/badge.svg",
    url: "https://www.justsimple.tools",
    alt: "Listed on JustSimple Tools",
    width: 150,
    height: 54,
    dofollow: true,
  },
  {
    name: "Dang.ai",
    image: "https://cdn.prod.website-files.com/63d8afd87da01fb58ea3fbcb/6487e2868c6c8f93b4828827_dang-badge.png",
    url: "https://dang.ai/",
    alt: "Dang.ai",
    width: 150,
    height: 54,
    dofollow: true,
  },
  {
    name: "Findly.tools",
    image: "https://findly.tools/badges/findly-tools-badge-light.svg",
    url: "https://findly.tools/pinpoint-answer-today-1?utm_source=pinpoint-answer-today-1",
    alt: "Featured on Findly.tools",
    width: 150,
    height: 48,
    dofollow: true,
  },
  {
    name: "Good AI Tools",
    image: "https://goodaitools.com/assets/images/badge-dark.png",
    url: "https://goodaitools.com",
    alt: "Good AI Tools",
    width: 207,
    height: 54,
    dofollow: true,
  },
  {
    name: "ShinyLaunch",
    image: "https://shinylaunch.com/static/images/badge-dark.png",
    url: "https://shinylaunch.com",
    alt: "ShinyLaunch",
    width: 198,
    height: 54,
    dofollow: true,
  },
  {
    name: "Startup To Startup",
    image: "https://startuptostartup.com/badages-awards.svg",
    url: "https://startuptostartup.com",
    alt: "Featured on Startup To Startup",
    width: 250,
    height: 54,
    dofollow: true,
  },
  {
    name: "First Look",
    image: "https://firstlook.tools/badge/badge_dark.svg",
    url: "https://firstlook.tools",
    alt: "Featured on First Look",
    width: 160,
    height: 44,
    dofollow: true,
  },
  {
    name: "AI Just Better",
    image: "https://aijustbetter.com/badges/badge-dark.svg",
    url: "https://aijustbetter.com/item/pinpointanswertoday.app",
    alt: "Featured on AIJustBetter.com",
    width: 212,
    height: 55,
    dofollow: true,
  },
  {
    name: "Aidirs",
    image: "https://aidirs.best/light.svg",
    url: "https://aidirs.best",
    alt: "Featured on Aidirs",
    width: 200,
    height: 56,
    dofollow: true,
  },
  {
    name: "FreeAI",
    image: "https://www.freeai.run/badge/badge_dark.svg",
    url: "https://www.freeai.run",
    alt: "Featured on FreeAI",
    width: 153,
    height: 44,
    dofollow: true,
  },
  {
    name: "ToolRain",
    image: "https://toolrain.com/badges/badge-listed-light.svg",
    url: "https://toolrain.com/item/pinpoint-answer-today-pinpointanswertodayapp",
    alt: "Listed on ToolRain",
    width: 150,
    height: 44,
    dofollow: true,
  },
  {
    name: "The One Startup",
    image: "https://theonestartup.com/badages-awards.svg",
    url: "https://theonestartup.com",
    alt: "Featured on The One Startup",
    width: 230,
    height: 54,
    dofollow: true,
  },
  {
    name: "AI Finder",
    image: "https://aifinder.site/light-badge.png",
    url: "https://aifinder.site",
    alt: "Discover more AI tools at aifinder.site",
    width: 200,
    height: 69,
    dofollow: true,
  },
  {
    name: "Top Free Alternative",
    image: "https://www.topfreealternative.com/topfreealternative.com.jpg",
    url: "https://www.topfreealternative.com/",
    alt: "Featured on topfreealternative",
    width: 220,
    height: 50,
    dofollow: true,
  },
  {
    name: "SaaSHub",
    image: "https://cdn-b.saashub.com/img/badges/approved-neutral.png?v=1",
    url: "https://www.saashub.com/pinpointanswer-today?utm_source=badge&utm_campaign=badge&utm_content=pinpointanswer-today&badge_variant=neutral&badge_kind=approved",
    alt: "PinpointAnswerToday listed on SaaSHub",
    width: 150,
    height: 36,
  },
  {
    name: "Startup Inspire",
    image: "https://www.startupinspire.com/assets/images/badge_1.svg",
    url: "https://www.startupinspire.com",
    alt: "Featured on Startup Inspire",
    width: 140,
    height: 36,
  },
  {
    name: "Startup Fame",
    image: "https://startupfa.me/badges/featured-badge-small.webp",
    url: "https://startupfa.me",
    alt: "Featured on Startup Fame",
    width: 224,
    height: 36,
    dofollow: true,
  },
  {
    name: "Startup Fast",
    image: "https://startupfa.st/images/badges/powered-by-light.svg",
    url: "https://startupfa.st",
    alt: "Powered by Startup Fast",
    width: 150,
    height: 44,
    dofollow: true,
  },
  {
    name: "Toolfame",
    image: "https://toolfame.com/badge-light.svg",
    url: "https://toolfame.com/item/pinpoint-answer-today",
    alt: "Featured on Toolfame",
    width: 140,
    height: 54,
    dofollow: true,
  },
  {
    name: "Submito",
    image: "https://submito.net/badge/listed-dark.svg",
    url: "https://submito.net",
    alt: "Listed on Submito",
    width: 120,
    height: 36,
  },
  {
    name: "SaaSFame",
    image: "https://saasfame.com/badge-light.svg",
    url: "https://saasfame.com/item/pinpoint-answer-today",
    alt: "Listed on SaaSFame",
    width: 130,
    height: 36,
    dofollow: true,
  },
  {
    name: "Bestsky Tools",
    image: "https://assets.bestsky.tools/badges/featured-light.svg",
    url: "https://bestsky.tools?utm_source=badge",
    alt: "Featured on BestskyTools",
    width: 150,
    height: 36,
    dofollow: true,
    rel: "",
  },
  {
    name: "Twelve Tools",
    image: "https://twelve.tools/badge0-white.svg",
    url: "https://twelve.tools",
    alt: "Listed on Twelve Tools",
    width: 120,
    height: 36,
  },
  {
    name: "Acid Tools",
    image: "https://acidtools.com/assets/images/badge-dark.png",
    url: "https://acidtools.com",
    alt: "Listed on Acid Tools",
    width: 120,
    height: 36,
    dofollow: true,
  },
] satisfies FooterBadge[];
